name: Flutter Nightly Build pc

on:
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build-pc.yml
    secrets: inherit
    with:
      upload-artifact: true
